Repository Folody-Team/Shartube, pull requests merged in 2022-08, with the labels that each got.

#67 Cannot return null for non-nullable field Query._entities #65
  server/comic/util/getUserByID.go
  server/docker-compose.yml
  server/user/src/resolvers/index.ts
  server/user/src/typeDefs/index.ts
Labels: bug

#68 SSl server (#66)
  .vscode/settings.json
  server/comic/.gitignore
  server/comic/secure/cert-gen.c
  server/comic/secure/run.sh
  server/comic/server.go
  server/graphql-gateway/.dockerignore
  server/graphql-gateway/package-lock.json
  server/socket/.gitignore
Labels: feature

#71 Delete comic, chap, session, image,... #57
  server/comic/database/base_model/base_model.go
  server/comic/graphql/generated/generated.go
  server/comic/graphql/model/models_gen.go
  server/comic/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/comic/graphql/resolver/comic.schema.resolvers.go
  server/comic/graphql/resolver/session.comic.schema.resolvers.go
  server/comic/graphql/schema/chap.session.comic.schema.graphqls
  server/comic/graphql/schema/comic.schema.graphqls
  server/comic/graphql/schema/session.comic.schema.graphqls
  server/comic/util/deleteUtil/chap.go
  server/comic/util/deleteUtil/comic.go
  server/comic/util/deleteUtil/session.go
Labels: feature

#74 fix some bug
  server/comic/database/base_model/base_model.go
  server/comic/database/comic_chap_model/comic_chap_model.go
  server/comic/database/comic_model/comic_model.go
  server/comic/database/comic_session_model/comic_session_model.go
  server/comic/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/comic/graphql/resolver/comic.schema.resolvers.go
  server/comic/graphql/resolver/resolver.go
  server/comic/graphql/resolver/session.comic.schema.resolvers.go
  server/comic/graphql/resolver/user.schema.resolvers.go
  server/comic/server.go
  server/comic/util/deleteUtil/chap.go
  server/comic/util/deleteUtil/comic.go
  server/comic/util/deleteUtil/session.go
  server/user/src/resolvers/index.ts
  server/user/src/util/client.ts
Labels: bug

#76 Test pending
  server/comic/database/base_model/base_model.go
  server/comic/database/comic_chap_model/comic_chap_model.go
  server/comic/database/comic_model/comic_model.go
  server/comic/database/comic_session_model/comic_session_model.go
  server/comic/graphql/generated/generated.go
  server/comic/graphql/model/models_gen.go
  server/comic/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/comic/graphql/resolver/comic.schema.resolvers.go
  server/comic/graphql/resolver/resolver.go
  server/comic/graphql/resolver/session.comic.schema.resolvers.go
  server/comic/graphql/resolver/user.schema.resolvers.go
  server/comic/graphql/schema/chap.session.comic.schema.graphqls
  server/comic/graphql/schema/comic.schema.graphqls
  server/comic/graphql/schema/session.comic.schema.graphqls
  server/comic/server.go
  server/comic/util/deleteUtil/chap.go
  server/comic/util/deleteUtil/comic.go
  server/comic/util/deleteUtil/session.go
  server/user/src/resolvers/index.ts
  server/user/src/util/client.ts
Labels: bug, enhancement, feature

#78 Added username check
  server/user/src/resolvers/index.ts
Labels: feature

#86 add delete image #85
  server/comic/go.mod
  server/comic/graphql/generated/generated.go
  server/comic/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/comic/graphql/resolver/comic.schema.resolvers.go
  server/comic/graphql/resolver/session.comic.schema.resolvers.go
  server/comic/graphql/schema/chap.session.comic.schema.graphqls
  server/comic/util/InSlice.go
Labels: enhancement, feature, go

#91 Develop
  server/comic/graphql/generated/generated.go
  server/comic/graphql/model/models_gen.go
  server/comic/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/comic/graphql/resolver/comic.schema.resolvers.go
  server/comic/graphql/resolver/session.comic.schema.resolvers.go
  server/comic/graphql/schema/comic.schema.graphqls
  server/comic/graphql/schema/session.comic.schema.graphqls
Labels: bug
