Repository Folody-Team/Shartube, pull requests merged in 2022-07, with the labels that each got.

#6 #5 converted net/http to mux
  server/go.mod
  server/go.sum
  server/server.go
Labels: enhancement

#9 pre make me query
  server/database/base_model/base_model.go
  server/database/session_model/session_model.go
  server/graphql/resolver/schema.resolvers.go
  server/graphql/resolver/user.schema.resolvers.go
  server/helper/token.go
  server/middleware/authMiddleware/auth.go
Labels: duplicate

#15 #11 (Create email detecter).
  server/graphql/resolver/user.schema.resolvers.go
Labels: enhancement

#18 10 create the comic by session
  server/database/session_model/session_model.go
  server/graphql/resolver/user.schema.resolvers.go
  server/helper/token.go
  server/middleware/authMiddleware/auth.go
  server/service/jwt.go
Labels: duplicate, enhancement

#19 2 make me query
  server/database/session_model/session_model.go
  server/graphql/resolver/schema.resolvers.go
  server/middleware/authMiddleware/auth.go
Labels: enhancement

#20 add inherits for graphql
  server/go.mod
  server/go.sum
  server/gqlgen.yml
  server/graphql/generated/generated.go
  server/graphql/model/models_gen.go
  server/graphql/resolver/schema.resolvers.go
  server/graphql/resolver/user.schema.resolvers.go
  server/graphql/schema/comic.schema.graphqls
  server/graphql/schema/schema.graphqls
  server/graphql/schema/user.schema.graphqls
  server/plugins/main.go
Labels: enhancement

#35 17 create comic model
  .github/FUNDING.yml
  server/.gitignore
  server/database/comic_model/comic_model.go
  server/directives/emailInput.go
  server/go.mod
  server/go.sum
  server/graphql/generated/generated.go
  server/graphql/model/models_gen.go
  server/graphql/resolver/user.schema.resolvers.go
  server/lib/javascript/pyscriptjs/.eslintrc.js
  server/lib/javascript/pyscriptjs/.prettierignore
  server/lib/javascript/pyscriptjs/.prettierrc.js
  server/lib/javascript/pyscriptjs/Makefile
  server/lib/javascript/pyscriptjs/README.md
  server/lib/javascript/pyscriptjs/environment.yml
  server/lib/javascript/pyscriptjs/package-lock.json
  server/lib/javascript/pyscriptjs/package.json
  server/lib/javascript/pyscriptjs/public/.gitkeep
  server/lib/javascript/pyscriptjs/rollup.config.js
  server/lib/javascript/pyscriptjs/src/App.svelte
  server/lib/javascript/pyscriptjs/src/components/base.ts
  server/lib/javascript/pyscriptjs/src/components/pybox.ts
  server/lib/javascript/pyscriptjs/src/components/pybutton.ts
  server/lib/javascript/pyscriptjs/src/components/pyconfig.ts
  server/lib/javascript/pyscriptjs/src/components/pyenv.ts
  server/lib/javascript/pyscriptjs/src/components/pyinputbox.ts
  server/lib/javascript/pyscriptjs/src/components/pyloader.ts
  server/lib/javascript/pyscriptjs/src/components/pyrepl.ts
  server/lib/javascript/pyscriptjs/src/components/pyscript.ts
  server/lib/javascript/pyscriptjs/src/components/pytitle.ts
  server/lib/javascript/pyscriptjs/src/interpreter.ts
  server/lib/javascript/pyscriptjs/src/main.ts
  server/lib/javascript/pyscriptjs/src/pyodide.ts
  server/lib/javascript/pyscriptjs/src/pyscript.py
  server/lib/javascript/pyscriptjs/src/stores.ts
  server/lib/javascript/pyscriptjs/src/styles/pyscript_base.css
  server/lib/javascript/pyscriptjs/src/utils.ts
  server/lib/javascript/pyscriptjs/tests/__init__.py
  server/lib/javascript/pyscriptjs/tests/conftest.py
  server/lib/javascript/pyscriptjs/tests/test_examples.py
  server/lib/javascript/pyscriptjs/tsconfig.json
  server/playground/playground.go
  server/static/css/graphiql.css
  server/static/js/graphiql.js
  server/static/lib/pyscript.css
  server/static/lib/pyscript.js
  server/static/lib/pyscript.js.map
  server/static/lib/pyscript.min.js
  server/static/lib/pyscript.min.js.map
  server/static/python/graphql.py
Labels: enhancement

#37 Merge branch 'main' of
  server/go.sum
  server/graphql/generated/generated.go
  server/graphql/model/models_gen.go
  server/lib/javascript/pyscriptjs/package-lock.json
  server/lib/javascript/pyscriptjs/package.json
Labels: bug

#43 Tritranduc/issue10
  .gitignore
  .vscode/configurationCache.log
  .vscode/dryrun.log
  .vscode/targets.log
  server/.gitignore
  server/database/base_model/base_model.go
  server/database/comic_chap_model/comic_chap_model.go
  server/database/comic_session_model/comic_session_model.go
  server/database/session_model/session_model.go
  server/gqlgen.yml
  server/graphql/generated/generated.go
  server/graphql/model/models_gen.go
  server/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/graphql/resolver/comic.schema.resolvers.go
  server/graphql/resolver/session.comic.schema.resolvers.go
  server/graphql/resolver/user.schema.resolvers.go
  server/graphql/schema/chap.session.comic.schema.graphqls
  server/graphql/schema/comic.schema.graphqls
  server/graphql/schema/schema.graphqls
  server/graphql/schema/session.comic.schema.graphqls
  server/graphql/schema/user.schema.graphqls
  server/middleware/authMiddleware/auth.go
  server/plugins/main.go
  server/util/getClient/getClient.go
Labels: enhancement

#44 10 create the comic by session
  .gitignore
  .vscode/configurationCache.log
  .vscode/dryrun.log
  .vscode/targets.log
  app/mobile/App.tsx
  server/.gitignore
  server/database/base_model/base_model.go
  server/database/comic_chap_model/comic_chap_model.go
  server/database/comic_session_model/comic_session_model.go
  server/database/session_model/session_model.go
  server/gqlgen.yml
  server/graphql/generated/generated.go
  server/graphql/model/models_gen.go
  server/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/graphql/resolver/comic.schema.resolvers.go
  server/graphql/resolver/session.comic.schema.resolvers.go
  server/graphql/resolver/user.schema.resolvers.go
  server/graphql/schema/chap.session.comic.schema.graphqls
  server/graphql/schema/comic.schema.graphqls
  server/graphql/schema/schema.graphqls
  server/graphql/schema/session.comic.schema.graphqls
  server/graphql/schema/user.schema.graphqls
  server/middleware/authMiddleware/auth.go
  server/plugins/main.go
  server/util/getClient/getClient.go
  web/pages/login/index.tsx
  web/pages/register/index.tsx
Labels: enhancement

#52 46 upload image to chapter
  .vscode/targets.log
  server/constraint/constraint.go
  server/database/base_model/base_model.go
  server/directives/auth.go
  server/directives/emailInput.go
  server/go.mod
  server/graphql/generated/generated.go
  server/graphql/model/models_gen.go
  server/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/graphql/resolver/comic.schema.resolvers.go
  server/graphql/resolver/session.comic.schema.resolvers.go
  server/graphql/resolver/user.schema.resolvers.go
  server/graphql/schema/chap.session.comic.schema.graphqls
  server/graphql/schema/comic.schema.graphqls
  server/graphql/schema/schema.graphqls
  server/graphql/schema/session.comic.schema.graphqls
  server/middleware/authMiddleware/auth.go
  server/middleware/passRequest/pass.go
  server/server.go
  server/testImage/doaremon_wdyw.jpg
  server/testImage/doraemons9_05_seriesdetailimagemobile-80424f74d030-1609395371290-iZgELVcX.png
  server/util/InSlice.go
  server/util/getClient/getClient.go
Labels: feature

#55 50 update name and description for comic chap session
  .vscode/targets.log
  server/Dockerfile
  server/docker-compose.yml
  server/go.sum
  server/graphql/generated/generated.go
  server/graphql/model/models_gen.go
  server/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/graphql/resolver/comic.schema.resolvers.go
  server/graphql/resolver/session.comic.schema.resolvers.go
  server/graphql/schema/chap.session.comic.schema.graphqls
  server/graphql/schema/comic.schema.graphqls
  server/graphql/schema/session.comic.schema.graphqls
Labels: feature

#60 58 create gateways http server
  server/api-gateway/.gitignore
  server/api-gateway/Cargo.lock
  server/api-gateway/Cargo.toml
  server/api-gateway/src/main.rs
  server/docker-compose.yml
  server/graphql-gateway/.dockerignore
  server/graphql-gateway/.gitignore
  server/graphql-gateway/dockerfile
  server/graphql-gateway/index.ts
  server/graphql-gateway/package.json
  server/graphql-gateway/tsconfig.json
  server/user/index.ts
Labels: help wanted

#63 Help me fix graphql gateway
  server/.vscode/settings.json
  server/comic/.env.example
  server/comic/directives/auth.go
  server/comic/go.mod
  server/comic/go.sum
  server/comic/graphql/generated/federation.go
  server/comic/graphql/generated/generated.go
  server/comic/graphql/model/models_gen.go
  server/comic/graphql/resolver/chap.session.comic.schema.resolvers.go
  server/comic/graphql/resolver/comic.schema.resolvers.go
  server/comic/graphql/resolver/entity.resolvers.go
  server/comic/graphql/resolver/session.comic.schema.resolvers.go
  server/comic/graphql/schema/user.schema.graphqls
  server/comic/service/jwt.go
  server/comic/util/getUserByID.go
  server/docker-compose.yml
  server/graphql-gateway/.vscode/settings.json
  server/graphql-gateway/index.ts
  server/socket/.gitignore
  server/socket/Cargo.lock
  server/socket/Cargo.toml
  server/socket/dockerfile
  server/socket/src/handler.rs
  server/socket/src/main.rs
  server/user/dockerfile
  server/user/src/function/emailChecker.ts
  server/user/src/index.ts
  server/user/src/resolvers/index.ts
  server/user/src/typeDefs/index.ts
Labels: bug
